-- MySQL Script generated by MySQL Workbench
-- Thu May  2 20:08:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CuidaBem2.0
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema CuidaBem2.0
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CuidaBem2.0` DEFAULT CHARACTER SET utf8 ;
USE `CuidaBem2.0` ;

-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Pacientes` (
  `ID_Paciente` INT NOT NULL AUTO_INCREMENT,
  `No_Cartao_Sus` CHAR(15) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Dt_nascimento` DATE NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Email` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_Paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Profissionais_Saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Profissionais_Saude` (
  `ID_Profissional` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Especializacao` VARCHAR(50) NOT NULL,
  `Registro_Profissional` VARCHAR(15) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_Profissional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Agenda_Atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Agenda_Atendimentos` (
  `ID_Escala` INT NOT NULL AUTO_INCREMENT,
  `Data_Agenda` DATE NOT NULL,
  `Horario_Inicio` TIME NOT NULL,
  `Duracao_Consulta` INT NOT NULL,
  `Status_Profissional` VARCHAR(20) NOT NULL,
  `Unidade_Atendimento` VARCHAR(50) NOT NULL,
  `Profissionais_saude_ID_Profissional` INT NOT NULL,
  PRIMARY KEY (`ID_Escala`, `Profissionais_saude_ID_Profissional`),
  INDEX `fk_Agenda_Atendimento_Profissionais_de_saude1_idx` (`Profissionais_saude_ID_Profissional` ASC),
  CONSTRAINT `fk_Agenda_Atendimento_Profissionais_de_saude1`
    FOREIGN KEY (`Profissionais_saude_ID_Profissional`)
    REFERENCES `CuidaBem2.0`.`Profissionais_Saude` (`ID_Profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Consultas` (
  `ID_Consulta` INT NOT NULL AUTO_INCREMENT,
  `Status_Consulta` VARCHAR(20) NOT NULL,
  `Observacoes` VARCHAR(200) NULL,
  `Registro_Consulta` TEXT NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  `Agenda_Atendimento_ID_Escala` INT NOT NULL,
  `Agenda_Atendimento_Profissionais_saude_ID_Profissional` INT NOT NULL,
  PRIMARY KEY (`ID_Consulta`, `Paciente_ID_paciente`, `Agenda_Atendimento_ID_Escala`, `Agenda_Atendimento_Profissionais_saude_ID_Profissional`),
  INDEX `fk_Agendamentos_Paciente_idx` (`Paciente_ID_paciente` ASC),
  INDEX `fk_Consultas_Agenda_Atendimento1_idx` (`Agenda_Atendimento_ID_Escala` ASC, `Agenda_Atendimento_Profissionais_saude_ID_Profissional` ASC),
  CONSTRAINT `fk_Agendamentos_Paciente`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `CuidaBem2.0`.`Pacientes` (`ID_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Agenda_Atendimento1`
    FOREIGN KEY (`Agenda_Atendimento_ID_Escala` , `Agenda_Atendimento_Profissionais_saude_ID_Profissional`)
    REFERENCES `CuidaBem2.0`.`Agenda_Atendimentos` (`ID_Escala` , `Profissionais_saude_ID_Profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Medicamentos` (
  `ID_Medicamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Composicao` VARCHAR(100) NULL,
  `Quantidade_Estoque` INT NOT NULL,
  `Quantidade_Pedido` INT NOT NULL,
  PRIMARY KEY (`ID_Medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Enderecos` (
  `ID_endereco` INT NOT NULL AUTO_INCREMENT,
  `Logradouro` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(5) NOT NULL,
  `Complemento` VARCHAR(10) NULL,
  `Bairro` VARCHAR(50) NOT NULL,
  `Cep` INT(8) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `Paciente_ID_Paciente` INT NOT NULL,
  PRIMARY KEY (`ID_endereco`, `Paciente_ID_Paciente`),
  INDEX `fk_Endereco_Paciente1_idx` (`Paciente_ID_Paciente` ASC),
  CONSTRAINT `fk_Endereco_Paciente1`
    FOREIGN KEY (`Paciente_ID_Paciente`)
    REFERENCES `CuidaBem2.0`.`Pacientes` (`ID_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Tratamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Tratamentos` (
  `ID_Tratamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Descricao` VARCHAR(200) NOT NULL,
  `Duracao_Dias` INT NOT NULL,
  `Consultas_ID_Consulta` INT NOT NULL,
  `Consultas_Paciente_ID_paciente` INT NOT NULL,
  `Consultas_Agenda_Atendimento_ID_Escala` INT NOT NULL,
  `Consultas_Agenda_Atendimento_Profissionais_saude_ID_Profissional` INT NOT NULL,
  `Inicio_Tratamento` DATE NOT NULL,
  PRIMARY KEY (`ID_Tratamento`, `Consultas_ID_Consulta`, `Consultas_Paciente_ID_paciente`, `Consultas_Agenda_Atendimento_ID_Escala`, `Consultas_Agenda_Atendimento_Profissionais_saude_ID_Profissional`),
  INDEX `fk_Tratamentos_Consultas1_idx` (`Consultas_ID_Consulta` ASC, `Consultas_Paciente_ID_paciente` ASC, `Consultas_Agenda_Atendimento_ID_Escala` ASC, `Consultas_Agenda_Atendimento_Profissionais_saude_ID_Profissional` ASC),
  CONSTRAINT `fk_Tratamentos_Consultas1`
    FOREIGN KEY (`Consultas_ID_Consulta` , `Consultas_Paciente_ID_paciente` , `Consultas_Agenda_Atendimento_ID_Escala` , `Consultas_Agenda_Atendimento_Profissionais_saude_ID_Profissional`)
    REFERENCES `CuidaBem2.0`.`Consultas` (`ID_Consulta` , `Paciente_ID_paciente` , `Agenda_Atendimento_ID_Escala` , `Agenda_Atendimento_Profissionais_saude_ID_Profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CuidaBem2.0`.`Tratamentos_has_Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CuidaBem2.0`.`Tratamentos_has_Medicamentos` (
  `Tratamentos_ID_Tratamento` INT NOT NULL,
  `Medicamentos_ID_Medicamento` INT NOT NULL,
  PRIMARY KEY (`Tratamentos_ID_Tratamento`, `Medicamentos_ID_Medicamento`),
  INDEX `fk_Tratamentos_has_Medicamentos_Medicamentos1_idx` (`Medicamentos_ID_Medicamento` ASC),
  INDEX `fk_Tratamentos_has_Medicamentos_Tratamentos1_idx` (`Tratamentos_ID_Tratamento` ASC),
  CONSTRAINT `fk_Tratamentos_has_Medicamentos_Tratamentos1`
    FOREIGN KEY (`Tratamentos_ID_Tratamento`)
    REFERENCES `CuidaBem2.0`.`Tratamentos` (`ID_Tratamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tratamentos_has_Medicamentos_Medicamentos1`
    FOREIGN KEY (`Medicamentos_ID_Medicamento`)
    REFERENCES `CuidaBem2.0`.`Medicamentos` (`ID_Medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
